### ISSUE TITLE
Review code

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-filecoin-rs#10]

**Comment by becominginsane** [comment]
Here's a list of possible improvements:
- [ ] Move from `quick-error` to `thiserror` and `anyhow`
- [ ] Move from `lazy_static` to `once_cell`
- [ ] Remove unnecessary `extern crate`
- [ ] Move from `secp256k1` to `k256` 
- [ ] Substitute `utils` module with `hex` crate
- [ ] Refactor INS constants into enum
- [ ] `blake2b_simd` is only used in integration tests
- [ ] `sha2` is unused
- [ ] `matches` is already present in the standard library

Here's a list of possible issues:
- [ ] Presence of `unsafe impl Send` for `FilecoinApp`, which should be `Send` automatically
